ffmpeg-php.lo: /home/lord2800/ffmpeg-php/ffmpeg-php/ffmpeg-php.c
	$(LIBTOOL) --mode=compile $(CC) $(GDLIB_CFLAGS) -I. -I/home/lord2800/ffmpeg-php/ffmpeg-php $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lord2800/ffmpeg-php/ffmpeg-php/ffmpeg-php.c -o ffmpeg-php.lo 
ffmpeg_movie.lo: /home/lord2800/ffmpeg-php/ffmpeg-php/ffmpeg_movie.c
	$(LIBTOOL) --mode=compile $(CC) $(GDLIB_CFLAGS) -I. -I/home/lord2800/ffmpeg-php/ffmpeg-php $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lord2800/ffmpeg-php/ffmpeg-php/ffmpeg_movie.c -o ffmpeg_movie.lo 
ffmpeg_frame.lo: /home/lord2800/ffmpeg-php/ffmpeg-php/ffmpeg_frame.c
	$(LIBTOOL) --mode=compile $(CC) $(GDLIB_CFLAGS) -I. -I/home/lord2800/ffmpeg-php/ffmpeg-php $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lord2800/ffmpeg-php/ffmpeg-php/ffmpeg_frame.c -o ffmpeg_frame.lo 
ffmpeg_errorhandler.lo: /home/lord2800/ffmpeg-php/ffmpeg-php/ffmpeg_errorhandler.c
	$(LIBTOOL) --mode=compile $(CC) $(GDLIB_CFLAGS) -I. -I/home/lord2800/ffmpeg-php/ffmpeg-php $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lord2800/ffmpeg-php/ffmpeg-php/ffmpeg_errorhandler.c -o ffmpeg_errorhandler.lo 
ffmpeg_tools.lo: /home/lord2800/ffmpeg-php/ffmpeg-php/ffmpeg_tools.c
	$(LIBTOOL) --mode=compile $(CC) $(GDLIB_CFLAGS) -I. -I/home/lord2800/ffmpeg-php/ffmpeg-php $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lord2800/ffmpeg-php/ffmpeg-php/ffmpeg_tools.c -o ffmpeg_tools.lo 
$(phplibdir)/ffmpeg.la: ./ffmpeg.la
	$(LIBTOOL) --mode=install cp ./ffmpeg.la $(phplibdir)

./ffmpeg.la: $(shared_objects_ffmpeg) $(FFMPEG_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_ffmpeg) $(FFMPEG_SHARED_LIBADD)

